from collections.abc import Coroutine
from typing import Any

from pydantic import BaseModel

from ._base import HttpError as HttpError
from ._base import PreparedRequest as PreparedRequest
from ._base import prepare_request as prepare_request
from ._responses import BytesResponse as BytesResponse
from ._responses import TextResponse as TextResponse
from ._types import EndpointInfo as EndpointInfo
from ._types import ExtractedEndpoint as ExtractedEndpoint
from ._types import RequestStyle as RequestStyle
from ._types import ResponseStyle as ResponseStyle
from .async_client import AsyncAPIClient as AsyncAPIClient
from .backends import AsyncHttpBackend as AsyncHttpBackend
from .backends import HttpBackend as HttpBackend
from .backends import HttpResponse as HttpResponse
from .client import APIClient as APIClient

class Endpoint[TRequest: BaseModel, TResponse: BaseModel | None]:
    def __call__(self, request: TRequest) -> TResponse: ...

class Get[TRequest: BaseModel, TResponse: BaseModel | None, TPath: str](Endpoint[TRequest, TResponse]): ...
class Post[TRequest: BaseModel, TResponse: BaseModel | None, TPath: str](Endpoint[TRequest, TResponse]): ...
class Put[TRequest: BaseModel, TResponse: BaseModel | None, TPath: str](Endpoint[TRequest, TResponse]): ...
class Patch[TRequest: BaseModel, TResponse: BaseModel | None, TPath: str](Endpoint[TRequest, TResponse]): ...
class Delete[TRequest: BaseModel, TResponse: BaseModel | None, TPath: str](Endpoint[TRequest, TResponse]): ...

class AsyncEndpoint[TRequest: BaseModel, TResponse: BaseModel | None]:
    def __call__(self, request: TRequest) -> Coroutine[Any, Any, TResponse]: ...

class AsyncGet[TRequest: BaseModel, TResponse: BaseModel | None, TPath: str](AsyncEndpoint[TRequest, TResponse]): ...
class AsyncPost[TRequest: BaseModel, TResponse: BaseModel | None, TPath: str](AsyncEndpoint[TRequest, TResponse]): ...
class AsyncPut[TRequest: BaseModel, TResponse: BaseModel | None, TPath: str](AsyncEndpoint[TRequest, TResponse]): ...
class AsyncPatch[TRequest: BaseModel, TResponse: BaseModel | None, TPath: str](AsyncEndpoint[TRequest, TResponse]): ...
class AsyncDelete[TRequest: BaseModel, TResponse: BaseModel | None, TPath: str](AsyncEndpoint[TRequest, TResponse]): ...

def extract_endpoint_info(hint: object) -> ExtractedEndpoint | None: ...
